require("config.treesitter")
require("config.telescope")
require("config.lsp")
require("config.cmp")
require("config.luasnip")
require("config.nvim-tree")
require("config.gitsigns")
require("config.mini")
require("config.bufferline")
-- require("config.symbols-outline")
-- require("config.galaxyline")
-- require("config.trouble")
-- require("config.autopairs")
-- require("config.comment")
